/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_hxc_imgrecognition_processActivity */

#ifndef _Included_cn_hxc_imgrecognition_processActivity
#define _Included_cn_hxc_imgrecognition_processActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hxc_imgrecognition_processActivity
 * Method:    removeNoise
 * Signature: ([III)[I
// */
//JNIEXPORT jintArray JNICALL Java_cn_hxc_imgrecognition_processActivity_removeNoise
//  (JNIEnv *, jobject, jintArray, jint, jint);
//
///*
// * Class:     cn_hxc_imgrecognition_processActivity
// * Method:    callstr
// * Signature: ()I
// */
//JNIEXPORT jint JNICALL Java_cn_hxc_imgrecognition_processActivity_callstr
//  (JNIEnv *, jobject);

/*
 * Class:     cn_hxc_imgrecognition_processActivity
 * Method:    callint
 * Signature: ([I)V
 */
JNIEXPORT jstring JNICALL Java_cn_hxc_imgrecognition_processActivity_callint
  (JNIEnv *, jobject, jintArray, jint width, jint height,jstring num,jstring win2,jstring whi2,jstring model,jint flag);

#ifdef __cplusplus
}
#endif
#endif
